info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T02:37:19.688Z"}
info: Connected to the database. {"timestamp":"2022-07-05T02:37:19.743Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T09:28:19.968Z"}
info: Connected to the database. {"timestamp":"2022-07-05T09:28:20.530Z"}
error: 
    status - 500 
    message - ReferenceError: findOne is not defined
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:31)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.forgetPassword (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:28)
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:66:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/forgetPassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-05T09:29:06.401Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T09:30:32.617Z"}
info: Connected to the database. {"timestamp":"2022-07-05T09:30:32.642Z"}
error: 
    status - 500 
    message - ReferenceError: find is not defined
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:31)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.forgetPassword (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:28)
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:66:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/forgetPassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-05T09:30:36.505Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T09:30:48.567Z"}
info: Connected to the database. {"timestamp":"2022-07-05T09:30:48.609Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T09:41:39.699Z"}
info: Connected to the database. {"timestamp":"2022-07-05T09:41:39.738Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T09:41:58.789Z"}
info: Connected to the database. {"timestamp":"2022-07-05T09:41:58.832Z"}
error: 
    status - 500 
    message - ReferenceError: findOne is not defined
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:31)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.forgetPassword (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:28)
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:66:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/forgetPassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-05T09:42:02.471Z"}
error: 
    status - 500 
    message - ReferenceError: findOne is not defined
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:31)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.forgetPassword (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:40:28)
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\controllers\/user.controller.js:66:36)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/forgetPassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-05T09:43:23.133Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T09:46:44.311Z"}
info: Connected to the database. {"timestamp":"2022-07-05T09:46:44.347Z"}
error: 
    status - 500 
    message - Error: Mail Id not present
    at _callee4$ (C:\Users\Arpan suji\FundooNotes\Fundoonotes\src\services\/user.service.js:46:13)
    at tryCatch (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\Arpan suji\FundooNotes\Fundoonotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/forgetPassword 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-05T09:46:51.224Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T09:50:14.129Z"}
info: Connected to the database. {"timestamp":"2022-07-05T09:50:14.260Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T14:03:48.269Z"}
info: Connected to the database. {"timestamp":"2022-07-05T14:03:48.428Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T14:31:28.594Z"}
info: Connected to the database. {"timestamp":"2022-07-05T14:31:28.632Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T14:35:32.308Z"}
info: Connected to the database. {"timestamp":"2022-07-05T14:35:32.384Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T14:38:11.501Z"}
info: Connected to the database. {"timestamp":"2022-07-05T14:38:11.547Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T14:40:06.002Z"}
info: Connected to the database. {"timestamp":"2022-07-05T14:40:06.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T14:40:19.962Z"}
info: Connected to the database. {"timestamp":"2022-07-05T14:40:20.038Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:00:24.128Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:00:24.157Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:04:43.384Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:04:43.418Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:05:34.035Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:05:34.097Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:08:00.811Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:08:00.836Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:09:05.137Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:09:05.165Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:13:44.116Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:13:44.163Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:19:52.512Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:19:52.541Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:23:59.887Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:23:59.918Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:30:10.969Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:30:10.995Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:33:09.604Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:33:09.638Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T15:35:10.506Z"}
info: Connected to the database. {"timestamp":"2022-07-05T15:35:10.562Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:31:30.281Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:31:30.317Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:39:05.720Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:39:05.743Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:41:49.894Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:41:49.926Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:42:55.282Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:42:55.310Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:49:23.161Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:49:23.195Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:49:59.442Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:49:59.469Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:52:20.821Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:52:20.843Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:53:17.362Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:53:17.411Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:53:55.302Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:53:55.330Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T16:55:00.287Z"}
info: Connected to the database. {"timestamp":"2022-07-05T16:55:00.331Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-05T17:49:27.941Z"}
info: Connected to the database. {"timestamp":"2022-07-05T17:49:27.986Z"}
